export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as AdminHeader } from './AdminHeader'
export {default as AdminFooter} from './AdminFooter'
export {default as Hero} from './Hero'
export {default as FeaturedSection} from './FeaturedSection'
export {default as BlurCircle} from './BlurCircle'
export {default as MovieCard} from './MovieCard'
export {default as TrailerSection} from './TrailerSection'
export {default as FavoriteCast} from './FavoriteCast'

